version: '3'

services:
  nginx:
    image: nginx:1.15.5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/
      - ./html:/var/www/html/
    restart: always
    links:
      - php-fpm

  php-fpm:
#    build: php-fpm
    image: php:5.6-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./html:/var/www/html/
    #      - ./html:/home/focusm/repo/fmichinahomepage/html
    env_file:
      - .env
    restart: always
